[greenclip]
    blacklisted_applications = []
    enable_image_support = true
    history_file = "${XDG_DATA_HOME}/greenclip/greenclip.hist"
    image_cache_directory = "/tmp/greenclip"
    max_history_length = 15
    max_selection_size_bytes = 0
    static_history = []
    trim_space_from_selection = true
    use_primary_selection_as_input = false
