[greenclip]
    blacklisted_applications = []
    enable_image_support = true
    history_file = "/tmp/greenclip-1000/text.hist"
    image_cache_directory = "/tmp/greenclip-1000/image"
    max_history_length = 15
    max_selection_size_bytes = 0
    static_history = []
    trim_space_from_selection = false
    use_primary_selection_as_input = false
